### ISSUE TITLE
Cannot upload file.

### ISSUE THREAD

**Issue by OUeasley** [sebassoft2/cribl-th-test-file-upload#1]
Download tgz
` curl https://cdn.cribl.io/dl/3.0.2/cribl-3.0.2-d2e1b4fe-linux-x64.tgz --output test.tgz`
Upload file 
` curl -F 'file=@/Users/bryceeasley/Downloads/test.tgz' http://localhost:3000/file/upload  -v`

Result:
File not upload
Expected Result:
File Uploaded

**Comment by OUeasley** [comment]
This seems to be an issue that the upload folder needs to be in place before the application starts. Perhaps we can implement a folder check on startup?

**Comment by sebassoft2** [comment]
> This seems to be an issue that the upload folder needs to be in place before the application starts. Perhaps we can implement a folder check on startup?

This was fixed. I've added a verification and creation at startup and a middleware to validate the upload folder on each call. Thanks for the suggestions 😄
